export const environment = {
    wordList: [
        "Poker",
        "Cárie",
        "Embalagem",
        "Aranha",
        "Braçadeiras",
        "Cartões",
        "Lupa",
        "Aeroporto",
        "Rio",
        "Terra",
        "Casa",
        "Orangotango",
        "Calendário",
        "Xarope",
        "Pantufas",
        "Pé",
        "Dinheiro",
        "tartaruga",
        "Bebe",
        "Cama",
        "Mesa",
        "Castelo",
        "Balão",
        "Açúcar",
        "Saca-rolhas",
        "Rins",
        "Cigarro",
        "Árvore",
        "Isqueiro",
        "Cinzeiro",
        "Xarope",
        "Casa",
        "Garagem",
        "Leão",
        "Elefante",
        "Gato",
        "Papagaio",
        "Chinelo",
        "Pénis",
        "Vagina(útero)",
        "Bebe",
        "Pessoa",
        "Macaco",
        "Mesa",
        "Microfone",
        "Microondas",
        "Lava loiça",
        "Cama",
        "Carro",
        "Avião",
        "Comboio",
        "Autocarro",
        "Barco",
        "Pai Natal",
        "Submarino",
        "Porta",
        "Tabela basquete",
        "Tabela periódica",
        "Cobra",
        "Cabra",
        "Flor",
        "Espelho",
        "Sanita",
        "Jesus",
        "Volante",
        "Arma",
        "Tampão",
        "Língua",
        "Lábios",
        "Maçã",
        "Morango",
        "Garrafão",
        "Espada",
        "Estendal",
        "Tacho",
        "YouTube",
        "Tinder",
        "CD",
        "Cassete música",
        "LGBT",
        "Sexo",
        "Disquete",
        "Cadeira",
        "Chávena",
        "Bumbum",
        "Cafeteira",
        "Camisola",
        "Calças",
        "Sapatos",
        "Batatas fritas",
        "Abacaxi",
        "Amendoim",
        "Carro de compras",
        "Betoneira",
        "Balde",
        "Colher",
        "Inchada",
        "Poster",
        "Alicate",
        "Corta unhas",
        "Cavalo",
        "Desdentado",
        "Pavão",
        "Galinha",
        "Avestruz",
        "Rinoceronte",
        "Tenda",
        "Lua",
        "Sol",
        "Igreja",
        "Castelo",
        "Caixão",
        "Vampiro",
        "Vibrador",
        "Algemas",
        "Chicote",
        "Plug anal",
        "Óculos de sol",
        "Chapéu de sol",
        "Bóia",
        "Sobrancelha",
        "Sutiã",
        "Cuecas",
        "Seios",
        "Lagarto",
        "Bolacha",
        "Fogueira",
        "Foguete",
        "Foguetão",
        "Chapéu",
        "Boné",
        "Sistema solar",
        "Estrelas",
        "Gaivotas",
        "Tubarão",
        "Baleia",
        "Ilha",
        "Dado",
        "Hélice",
        "Pirilampo",
        "Escorpião",
        "Borboleta",
        "Abelha",
        "Harry potter",
        "Tatuagem",
        "Rosa dos ventos",
        "Espada",
        "Faca",
        "Fotografia",
        "Olho",
        "Astronauta",
        "Globo",
        "Teia de aranha",
        "Aranha",
        "Arame farpado",
        "Lâmpada",
        "Cebola",
        "Apito",
        "Coroa",
        "Bandeira",
        "Veado",
        "Guitarra",
        "Campo de futebol",
        "Piano",
        "Ovo estrelado",
        "Coluna música",
        "Megafone",
        "Holofote",
        "Candeeiro",
        "Palco",
        "Muletas",
        "Cadeira de rodas",
        "Meias",
        "Trenó",
        "Presente",
        "Chouriço",
        "Frango churrasco",
        "Carica de cerveja",
        "Ninho",
        "Peluche",
        "Duche/chuveiro",
        "Banheira",
        "Torneira",
        "Antena",
        "Vaso",
        "Sofá",
        "Escadas",
        "Limão",
        "Mar/oceano",
        "Corrimão",
        "Esgoto",
        "Mangueira",
        "Ampulheta",
        "Termómetro",
        "Anzol",
        "Comprimido",
        "Cadeado",
        "Dentadura",
        "Corrente",
        "Bússola",
        "Folha",
        "Despertador",
        "Mola de carro",
        "Batom",
        "Vassoura",
        "Verniz",
        "Extintor",
        "Penso rápido",
        "Flauta",
        "Cogumelo",
        "Raquete",
        "Espermatozóide",
        "Incenso",
        "iô iô",
        "Laço",
        "Fogo",
        "Luva",
        "Mão",
        "Pés",
        "Martelo",
        "Ovni",
        "Pneu",
        "Seringa",
        "Skate",
        "Tambor",
        "Teclado",
        "Tijolo",
        "Troféu",
        "Bola futebol",
        "Ventoinha",
        "Lareira",
        "Xadrez",
        "Foca",
        "Xilofone",
        "Pamdeireta",
        "Saxofone",
        "Cacho uvas",
        "Pica-pau",
        "Estante",
        "Montanha",
        "Lagoa",
        "Balão",
        "Envelope",
        "Selo",
        "Carimbo",
        "Vela",
        "Caneta",
        "Lápis",
        "Borracha",
        "Escova de dentes",
        "Jangada",
        "Prancha",
        "Jaula",
        "Caixote lixo",
        "Patins",
        "Chave",
        "Medalha",
        "Parafuso",
        "Rede pesca",
        "Cana de pesca",
        "Retrovisor",
        "Cerveja",
        "Trepadeira",
        "Azuleijo",
        "Fogão",
        "Esfregona",
        "Mamilo",
        "Cabide/cruzeta",
        "Código de barras",
        "Prisioneiro",
        "Compasso",
        "Régua",
        "T-rex",
        "Tesoura",
        "Tartaruga",
        "Sino",
        "Buvuzela",
        "Dinheiro",
        "Agrafador",
        "Almofada",
        "Berbequim",
        "Canabis",
        "Fonte",
        "Caldeirão",
        "Mapa",
        "Pionés",
        "Pirâmide",
        "Múmia",
        "Sabonete",
        "Champô",
        "Bolhas de sabão",
        "Coração",
        "Osso",
        "Espinhas",
        "Ralador",
        "Cenoura",
        "Colmeia",
        "Nabo",
        "Cebola",
        "Rímel",
        "Dragão",
        "Langerie",
        "Trampolim",
        "SLB",
        "SCP",
        "FCP",
        "Escova cabelo",
        "Abafador",
        "Máscara COVID",
        "Mosca",
        "Cócó",
        "Relâmpago/raio",
        "Stop",
        "Janela",
        "Câmera fotográfica",
        "Cavalo marinho",
        "Caracol",
        "Pulga",
        "Sapo",
        "Cegonha",
        "Crocodilo",
        "Girafa",
        "Cacto",
        "Camelo",
        "Lago"
        ],
    apiUrl: "https://europe-west2-draw-drinking-game.cloudfunctions.net/app"
};
