export const environment = {
    wordList: [
        "sol",
        "lua",
        "estrela",
        "nuvem",
        "flor",
        "árvore",
        "casa",
        "montanha",
        "coração",
        "peixe",
        "pássaro",
        "gato",
        "cachorro",
        "carro",
        "avião",
        "balão",
        "foguete",
        "livro",
        "copo",
        "caderno",
        "bola",
        "chapéu",
        "relógio",
        "lápis",
        "caneta",
        "pente",
        "borboleta",
        "mão",
        "rosto",
        "olho",
        "árvore de natal",
        "cubo",
        "pirâmide",
        "círculo",
        "triângulo",
        "quadrado",
        "câmera",
        "lâmpada",
        "escada",
        "janela",
        "porta",
        "garrafa",
        "chave",
        "moeda",
        "cadeira",
        "mesa",
        "sanduíche",
        "pizza",
        "morango",
        "maçã",
        "banana",
        "limão",
        "laranja",
        "melancia",
        "pipoca",
        "sorvete",
        "livro",
        "telefone",
        "computador",
        "caixa",
        "chaveiro",
        "violão",
        "violino",
        "martelo",
        "escova de dentes",
        "pasta de dentes",
        "árvore de natal",
        "guarda-chuva",
        "bicicleta",
        "patins",
        "bala",
        "fita adesiva",
        "presente",
        "vela",
        "envelope",
        "cartão",
        "ventilador",
        "câmera",
        "colher",
        "garfo",
        "faca",
        "xícara","Baloiço","Casaco","Calçado","Oceano","Cão","Boca","Leite","Pato","Skate","Pássaro","Rato","Baleia","Casaco","Camisa","Hipopótamo","Praia","Ovo","Biscoitos","Queijo","Pular","Tambor","Trabalhos de casa","cola","borracha","paz","pânico","alarme","longe","confortável","gotejamento","chato","quente","frio","pais","armário","rir","em queda","Dormida","calendário","protetor solar","Panda","detenção","cabelo","patinagem no gelo","medo","dicionário","homerun","flutuador de cerveja de raiz","hibernação","Varredora de rua","Spitball","bebedouro","imaginação","Irritado","Fogos de artifício","Abóbora","Bebé","Flor","Arco-íris","Barba","Disco voador","Reciclar","Bíblia","Girafa","Castelo de areia","Biquíni","Óculos","Flocos de neve","Livro","Salto alto","Escadas","Balde","Cone de sorvete","Estrela-do-mar","Abelha Bumble","Iglu","Morango","Borboleta","Bicho da senhora","Dom","Câmara","Lâmpada","Pneu","Gato","Leão","Brinde","Igreja","Caixa de correio","Escova de dentes","Lápis de cera","Noite","Pasta de dentes","Golfinho","Nariz","Camião","Ovo","Jogos Olímpicos","Voleibol","Torre Eiffel","Amendoim","meio cartão","remo","babá","gotejamento","champô","ponto","Máquina do tempo","Critério","Pense","dardos de renda","mundo","lixívia de abacate","chuveiro","cortina","amassado do cabo de extensão","colo de aniversário","Área restrita","nódoa negra","areia movediça","nevoeiro","gasolina","bolso","buzinar","esponja","aro","noiva","peruca","fecho de correr","","abridor de cartas","violino","búfalo de água","piloto","balde da marca","varinha","mascote da costela","bombeiro","pole zoo sushi","teto de gás","fã careca","Banister Punk","correios","época","Internet","xadrez","fantoche","carrilhão","Hera","aplausos","Aplicação","abacate","Prémio","Crachá","bagagem","padeiro","barbeiro","pechincha","carrinho","percevejos","bettle","mendigo","Aniversário","biscoito","lixívia","persianas","Bobsled","Bonnet","bookend","Limite","cérebro","nódoa negra","bolha","Cérebro","Gatinho","Parque Infantil","Banho de espuma","Kiwi","Torta de abóbora","Fecho de fivela","Batom","Gota de chuva","Ônibus","Lagosta","Robô","Acidente de viação","Pirulito","Castelo de areia","Castelo","Íman","Chinelo","Motosserra","Megafone","Bola-de-neve","Tenda de circo","Sereia","Aspersor","Computador","Minivan","Estátua da Liberdade","Berço","Monte Rushmore","Girino","Dragão","Música","Teepee","Halteres","Polo Norte","Telescópio","Enguia","Enfermeiro","Comboio","Roda gigante","Coruja","Triciclo","Bandeira","Chupeta","Tutu","Lixo eletrônico","Piano","Lixo","Parque","Pirata","Esqui","Apito","Estado","Beisebol","Carvão","Rainha","Fotografia","Computador","Hóquei","Cachorro-quente","Sal e pimenta","Esfábio","Rã","Cortador de relva","Colchão","Catavento","Bolo","Circo","Bateria","Carteiro","Vaqueiro","Palavra-passe","Harry Potter","Professor","George Washington","Justin Bieber","Batman","Bob Esponja","Zendaya","Super-Homem","Thomas"," o motor do tanque","Ariana Grande","Mulher-Maravilha","Presidente Donald Trump","Nemo","Pantera Negra","Tartarugas Ninja Mutantes Adolescentes","Incrível","Homem Aranha","Vampiro","Andi Mack","Capitão América","Selena Gomez","Banco traseiro","Cadeira alta","Banda de rock","Aniversário","Hóquei","Sasquatch","Buraco negro","O hotel","Ovos mexidos","Nevasca","Pular corda","Cinto de segurança","Burrito","Coala","Pular","Capitão","Leprechaun","Eclipse solar","Lustre","Leve","Espaço","Berço","Máscara","Estetoscópio","Navio de cruzeiro","Transportar","Executar","Salto","Nadar","Pular","Voo","Linha","Captura","Assista","Baloiço","Saiba mais","Amor","Bebida","Arroto","Comer","Ler","Tipo","Baixar","Ligar","Encaixe","Texto","Pose","Gritar","Dormir","Arranhão","Abraço","Corte","Bang","Espeto","Gravata","Aberto","Ouvir","Escrever","Cantar","Orar","Fechar","Dança","Expedição","Comércio","Conduzir","Unir-se","Multiplicar","Cozinheiro","Desligue a tomada","Compra","Mecânico","Cegonha","Dança","Mãe","Queimaduras solares","Desodorizante","Sr. Cabeça de Batata","Tópico","Linkedin","Meia-calça","Turista","Apartamento","Placa de papel","Estados Unidos","Moldura","Fotografia","Wi-Fi","Lua cheia","Pilgram","Zumbi","Jogo","Pirata","negócios","cabine","Cartão","carpinteiro","cenoura","catálogo","Teto","canal","carregador","líder de torcida","cozinheiro","xadrez","Castanha","carrilhão","Chuck Norris","penhasco","manto","entupimento","Treinador","comediante","confortável","Comerciais","monitor de computador","conversa","descapotável","vaqueiro","cãibras","criticar","cruzeiro","Migalhas","crosta","punho","cupcake","cortina","escuridão","dardos","Painel de instrumentos","Bicicleta","Skate","Eletricidade","Ladrão","Bule de chá","Profundo","Primavera","Natureza","Pouco profundo","Lá fora","América","Gravata borboleta","Cera","Lâmpada bulbo","Música","Picolé","Cérebro","Bolo de Aniversário","Joelho","Abacaxi","Tusk","Aspersor","Dinheiro","Esplanada","Farol","Capacho","Rosto","Flauta","Tapete","Bola-de-neve","Bolsa"
    ]
};
